### ISSUE TITLE
The declared functionality is not released

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataEasyExtendsBundle#112]
Hi.

The official manual page contains the description of the functionality, that is not released yet (see https://sonata-project.org/bundles/easy-extends/master/doc/reference/why.html)

I'm using `Symfony v3.2.7`. I decidet to use `SonataMediaBundle 3.5.1`, which requires `SonataEasyExtendsBundle ^2.1`. Then I read the documentation and saw, that I can use `--namespace` option of `:generate` command to customize the namespace:

```
Also note that the –namespace option allows you to choose the base namespace, such as Application\Sonata. Default destination is Application\:vendor.
```

But in the fact I **cannot** use the `--namespace` option, because the commit providing it (https://github.com/sonata-project/SonataEasyExtendsBundle/pull/80) is not released yet (the latest release 2.1.10 does not contain it).

**Comment by greg0ire** [comment]
See the `master` part in the url you are showing us? It means you are reading the documentation for master. Please read the documentation for 2.x

**Comment by vyshkant** [comment]
https://sonata-project.org/bundles/easy-extends/2-x/doc/reference/why.html tells the same:
```
Also note that the –namespace option allows you to choose the base namespace, such as Application\Sonata. Default destination is Application\:vendor.
```

**Comment by greg0ire** [comment]
Then maybe we just need a new release? The functionality is on 2.x, isn't it?

**Comment by greg0ire** [comment]
https://github.com/sonata-project/SonataEasyExtendsBundle/releases shows there are 119 commits since last release (!) I'll ask for a release rightaway

**Comment by vyshkant** [comment]
I'm not sure if all of the new functionality is on `2.x` branch, but the `--namespace` option is on it.

**Comment by vyshkant** [comment]
Not really 119 commits, because the `2.0.0` is only shown as the latest but is not latest. The latest is `2.1.10` (https://github.com/sonata-project/SonataEasyExtendsBundle/releases/tag/2.1.10) and there are 38 commits since it.
I think that `2.0.0` is decided (by github) as "latest" because it was made last (in time). But the last in commits hierarchy as I see is `2.1.10`.

**Comment by greg0ire** [comment]
Oh good, you're right! The functionality you are looking for still probably is in these 38 commits.

**Comment by vyshkant** [comment]
Yes, exactly.

**Comment by greg0ire** [comment]
A new release was created, please try it.

**Comment by vyshkant** [comment]
Thanks! There is also a problem with the backward compatibility of external bundles because of a lot of hardcode like `Application\Sonata\MediaBundle...` in theirs files.

For example, the compatibility with SonataMediaBundle had been broken: https://github.com/sonata-project/SonataMediaBundle/pull/1250
