### ISSUE TITLE
Symfony 3.4 Deprecated bundle inheritance

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataEasyExtendsBundle#152]
released Symfony 3.4 does show warning:
"User Deprecated: Bundle inheritance is deprecated as of 3.4 and will be removed in 4.0."

Blog about [that](https://symfony.com/blog/new-in-symfony-3-4-deprecated-bundle-inheritance)

after some change in debug output, it was shown that it was my ApplicationSonataUserBundle

i don't know in which part it makes this bundle useless, but the `getParent` in `bundle.mustache` need to be removed or return `null`

i did it for my own bundle, and it seems still to work

**Comment by core23** [comment]
Can you provide a PR with the first steps @Hanmac ?

**Comment by Hanmac** [comment]
@core23 do you mean like this?
the bundle inheritance doesn't seems to be used by sonata classes,
like in the blog link, it shows that is wasn't useful in the first place?
