### ISSUE TITLE
[RFC] Improve namespace for flex

### ISSUE THREAD

**Issue by Xymanek** [sonata-project/SonataEasyExtendsBundle#172]
The current generated namespace `App\Application\Sonata\XyzBundle` is very redundant and weird looking. A much more sensible namespace would be something like `App\Sonata\XyzBundle`.

Also (from what I was told on sf slack) it's completely fine to remap `[project root]/src` folder to another namespace. As such, it would be nice to support case when the "root" project namespace is something other than `App` and generate something like `AcmeCorp\Shop\Sonata\XyzBundle` (if the "root" namespace is `AcmeCorp\Shop`)

**Comment by covex-nn** [comment]
Applications with Flex are bundle-less. So everything starting from `Application` to the `XyzBundle` is redundant in `App\Application\Sonata\XyzBundle`

**Comment by jordisala1991** [comment]
> Also (from what I was told on sf slack) it's completely fine to remap [project root]/src folder to another namespace. As such, it would be nice to support case when the "root" project namespace is something other than App and generate something like AcmeCorp\Shop\Sonata\XyzBundle (if the "root" namespace is AcmeCorp\Shop)

This should be already doable using --namespace_prefix

**Comment by Xymanek** [comment]
> This should be already doable using --namespace_prefix

I meant that if this is reworked

**Comment by Xymanek** [comment]
@covex-nn Is it possible to provide the functionality without using bundles?

**Comment by covex-nn** [comment]
I think yes, it is possible!

IMO recipes for NotificationBundle or PageBundle must contain everything we need to launch them out from the box without any additional configuration. Additional configuration could be done after installation just to tune up that bundles, of course.

Please, see example https://github.com/covex-nn/recipes-contrib/commit/2e5da5cbe9121d9f4d53190c8d6036c2b15a9b07 - this commit is my future proposal, a recipe for NotificationBundle. It contains bundle configuration, entity class and serializer metadata configuration.

@kunicmarko20 wrote me in slack, that i am `forgetting the document and phpcr and the serialization config`. Serializer metadata configuration is not loaded by default right now, but i am working on it https://github.com/symfony/recipes-contrib/pull/293. And i hope that `document and phpcr` can be used without bundles too

**Comment by Xymanek** [comment]
Relevant discussion: https://github.com/sonata-project/dev-kit/issues/397
