### ISSUE TITLE
Deprecate this bundle

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataEasyExtendsBundle#237]
## Feature Request

Symfony flex is a better alternative to this bundle.

**Comment by franmomu** [comment]
It's used in:

- [ ]  SonataUserBundle
- [ ]  SonataUserBundle
- [ ]  SonataUserBundle
- [ ]  SonataUserBundle
- [ ]  SonataUserBundle
- [ ]  SonataUserBundle
- [ ]  SonataUserBundle

**Comment by core23** [comment]
There are two steps that should be done for each bundle:
- Remove `*.skeleton` files
- Use `doctrine-extensions` for late orm mapping

**Comment by VincentLanglet** [comment]
We can start with the README https://github.com/sonata-project/SonataEasyExtendsBundle/pull/248

**Comment by wbloszyk** [comment]
Can we remove it other bundles from composer where minimum symfony4 is require?

**Comment by jordisala1991** [comment]
I didn't saw this issue on this repository when I created the one in dev-kit. Let's continue there since it affects a lot of bundles. https://github.com/sonata-project/dev-kit/issues/750
