### ISSUE TITLE
Infinite loop of extended 

### ISSUE THREAD

**Issue by shkkmo** [sonata-project/SonataEasyExtendsBundle#59]
It's possible to get a weird infinite loop in the twig file loader if you have a template in a Application bundle that tries to extend the parent template of the exact same name. There should either be a check added to prevent this, or there should be a note added to the documentation to help make people aware of the possibility. (see: http://stackoverflow.com/a/29641032/1153227)

**Comment by core23** [comment]
This is no an `SonataEasyExtendsBundle` problem, but a twig / symfony problem.

**Comment by jordisala1991** [comment]
Not an issue of this bundle and also soon this generated bundles wont be related to the parent bundle
