### ISSUE TITLE
make "--dest src" the default instead of "--dest app"

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataEasyExtendsBundle#64]
what do you think?

Oskar

**Comment by rande** [comment]
I think; we also need to refactor the code to use the new AppBundle convention. See https://github.com/sonata-project/sandbox/tree/2.4-develop/src/AppBundle/Entity.

Having one AppBundle with all entities will be easier to install, and configure.

**Comment by OskarStark** [comment]
:+1:

**Comment by OskarStark** [comment]
Can you explain exactly what to change?

maybe i can provide a PR

**Comment by OskarStark** [comment]
ping @rande

**Comment by webdevilopers** [comment]
:+1 for new AppBundle convention @rande !

From the archives:
https://github.com/sonata-project/SonataEasyExtendsBundle/issues/3

**Comment by rande** [comment]
@webdevilopers yep, but this will require 2.0 branch as it is a major BC break. The Sonata Sandbox already support the AppBundle convention.

**Comment by webdevilopers** [comment]
Thanks for the update! Looking forward to this. Still interested in creating a PR / branch for that @OskarStark ?! ;)

**Comment by OskarStark** [comment]
yes, but currently no time :smile:

**Comment by webdevilopers** [comment]
A common problem these days! ;) But I guess this issue doesn't have such a high priority esp. since it is BC break and must wait for a new branch. And there is a workaround.

**Comment by OskarStark** [comment]
yes :smile: 

@webdevilopers would you like to contact me via skype?

**Comment by jordisala1991** [comment]
This is already the case, right? if not feel free to reopen
