### ISSUE TITLE
Add support for subfolders inside Entity folder

### ISSUE THREAD

**Issue by binhle410** [sonata-project/SonataEasyExtendsBundle#72]
currently, all the entities cannot be in nested folders.
So, it has to be like
src/Entity/EntityA.php

So, we need support for nested Entity folder like

src/Entity/Media/SoundMedia.php
src/Entity/Gallery/SoundGallery.php

what do you think?

**Comment by OskarStark** [comment]
You can provide a PR if you want, please don't forget to adjust the documentation, otherwise please close this issue

**Comment by core23** [comment]
This is even possible in doctrine?

**Comment by greg0ire** [comment]
@core23 It's not very easy but I think it is.

**Comment by OskarStark** [comment]
why did you close this issue @greg0ire ?

**Comment by greg0ire** [comment]
Because there is no feedback, I'll reopen if there is one, otherwise we will forget to do so.
